all: einheitskugel e_fkt

clear: 
	rm -rf einheitskugel.o e_fkt.o

einheitskugel: einheitskugel.cpp
	clear
	g++ einheitskugel.cpp -o einheitskugel.o

e_fkt: e_fkt.cpp
	clear
	g++ e_fkt.cpp -o e_fkt.o
