build: main.cpp random_walk.cpp functions.h random_walk_distance.cpp take_average.cpp help.cpp
	clear
	g++ take_average.cpp main.cpp random_walk.cpp random_walk_distance.cpp help.cpp -o random_walk.o 

